# General
screen_resolution: [1920, 1080]
directions:
    up: [-1, 0]
    down: [1, 0]
    left: [0, -1]
    right: [0, 1]

# Modes
mode_model: overlapping # Options: ['overlapping', 'simple_tiled', 'tiled']
mode_boundary_conditions: wrap_around # Options (based on chatgpt prompt): ['wrap_around', 'clamping', 'mirroring', 'noise']

# Paths
paths:
    # Directory where the bitmap .xlsx files are stored.
    bitmaps_dir: terrain_generation/wave_function_collapse/bitmaps/

# Bitmaps
bitmaps:
    city:
        # Dimensions of the bitmap specified in the number of cells
        # in width and height in the excel file.
        dimensions: [9, 9]
    flowers:
        dimensions: [24, 24]
    loop:
        dimensions: [16, 16]
    mountains:
        dimensions: [16, 16]
    network:
        dimensions: [16, 16]

# Exporting bitmaps as png
# When processing a bitmap from a .xlsx file, it is possible to export this .xlsx
# file as a .png, so that you also view the bitmap inside VSCode.
png_bitmap:
    # Determines if the excel bitmap will be export as png image.
    export: True
    # This parameter determines the bitmap_cell width and height values in number 
    # of pixels.
    cell_size: 30
    default_background_color: [0, 0, 0]