# This configuration file contains parameter that typically
# change values between several executions of the algorithm.

# File name of the input bitmap image.
file_name: city.xlsx

# Dimensions of the grid. This is equal to the width and height
# of the grid.
grid_dim: 40

# Similar to `grid_dim`, but now the dimensions of the tiles.
tile_dim: 3